### ISSUE TITLE
console.log messages do not appear in the output panel

### ISSUE THREAD

**Issue by optimuspaul** [tanepiper/SublimeText-Nodejs#44] opened 2013-09-26 01:32 UTC
I've installed the plugin and attempted to run some scripts.  No idea if they work because they don't output anything in the output panel.  Perhaps I'm doing something wrong, but it should be far more obvious what that is.

**Comment by varp** [comment] 2017-08-13 13:24
@shell @triffic-tang @optimuspaul Could you test the issue against latest release and the file _test_logging.js_ under _tests_ folder

**Comment by varp** [comment] 2017-10-20 07:16
The issue is fixed in the refactor branch

**Closed by varp** 2017-10-20 07:16 UTC
