### ISSUE TITLE
Debugger?

### ISSUE THREAD

**Issue by staryg** [tanepiper/SublimeText-Nodejs#66] opened 2017-06-26 07:20 UTC
I want to bump the issue #12 since the creator answered but he no longer works on this project, and then closed the issue. 

The debugger also uses node debug, which is deprecated. node inspect is supposed to be used instead.

**Comment by varp** [comment] 2017-06-26 08:16
Ok. Your issue has accepted. I'll give you feedback ASAP. I think it will be on this weekend.

**Comment by varp** [comment] 2017-07-11 11:19
@staryg Why you close this bug ?

**Comment by staryg** [comment] 2017-07-11 12:41
@varp sorry, my bad.

**Comment by varp** [comment] 2017-07-12 09:15
@staryg 😀  I'll dedicate this weekend to fixing the plugin bugs on the Windows platform

**Comment by varp** [comment] 2017-12-12 13:29
@staryg the issue is fixed in new release 2.0.0

**Closed by varp** 2017-12-12 13:29 UTC
