### ISSUE TITLE
'is_enabled must return a bool'

### ISSUE THREAD

**Issue by ncallister** [tanepiper/SublimeText-Nodejs#46] opened 2013-10-03 23:30 UTC
I'm setting up Sublime Text for the first time to start Node.js development and I can't get your nodejs plugin to run node.

I am running Sublime Text 3 "Stable Channel, Build 3047" and I installed the Nodejs package using Package Control.

Whenever I attempt to run my Node.js project (or even open the context menu I get the following on my console:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 445, in is_enabled_
raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Nodejs.Nodejs.NodeRunCommand object at 0x00000000036B3748>)
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 445, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Nodejs.Nodejs.NodeRunCommand object at 0x00000000036B3748>)
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 445, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Nodejs.Nodejs.NodeRunArgumentsCommand object at 0x00000000036B3400>)
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 445, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Nodejs.Nodejs.NodeRunArgumentsCommand object at 0x00000000036B3400>)
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 445, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Nodejs.Nodejs.NodeDrunCommand object at 0x00000000036B34E0>)
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 445, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Nodejs.Nodejs.NodeDrunCommand object at 0x00000000036B34E0>)
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 445, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Nodejs.Nodejs.NodeDrunArgumentsCommand object at 0x00000000036B3AC8>)
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 445, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Nodejs.Nodejs.NodeDrunArgumentsCommand object at 0x00000000036B3AC8>)
```

If someone could let me know what I have done wrong in the set up or how to work around this issue it would be much appreciated.

Thank you.

**Comment by varp** [comment] 2017-10-20 07:18
@phette23 @muke5hy @ncallister The problem is fixed in the refactor branch

**Closed by varp** 2017-10-20 07:18 UTC
