### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 325: illegal multibyte sequence

### ISSUE THREAD

**Issue by mayrino** [tanepiper/SublimeText-Nodejs#64] opened 2017-05-31 14:37 UTC
hello , i got a problem when i am used to npm module ,  i need help , thanks very much！ os:window 10 version:1607  sublime version: build 3126 

when i have running  every npm command , i always get below exception 

Exception in thread Thread-942:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\shuangmin\AppData\Roaming\Sublime Text 3\Packages\Nodejs\Nodejs.py", line 29, in run
    output = p.communicate()[0]
  File "./python3.3/subprocess.py", line 907, in communicate
  File "./python3.3/subprocess.py", line 479, in _eintr_retry_call
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 325: illegal multibyte sequence

**Comment by varp** [comment] 2017-06-02 15:33
Thx for feedback. Will "dig" on this weekend.

**Comment by mayrino** [comment] 2017-06-02 16:33
Thank you for reply. I have done the problem.
p definition  change to 
> p = subprocess.Popen(self.command,shell=False, stdout=subprocess.PIPE, cwd=self.working_dir,
          stderr=subprocess.STDOUT, **universal_newlines=False,** env=self.env)   
pay attention to universla_newlines=False  kwargs , 

ORIGINAL: universal_newlines=True enables text mode. Combined with stdout=PIPE, it forces decoding of the child process' output using locale.getpreferredencoding(False) that is not utf-8 on Windows. That is why raise UnicodeDecodeError.

Thanks for J.F. Sebastian  who wrote solution on stackoverflow [:](https://stackoverflow.com/questions/33283603/python-popen-communicate-str-encodeencoding-utf-8-errors-ignore-cr)

I had never before used python ,

**Comment by mayrino** [comment] 2017-06-02 16:39
J.F. Sebastian's  answer  link  [https://stackoverflow.com/questions/33283603/python-popen-communicate-str-encodeencoding-utf-8-errors-ignore-cr](url)

**Comment by varp** [comment] 2017-08-17 08:31
@mayrino I am planning to do grand refactor of the code. Be patient, please.

**Comment by elvenwhite** [comment] 2017-09-18 01:31
simply removing universal_newline or changing its value to False might cause error with multi-line code. 
I'd solved problem with adding .decode('utf-8') after p.communicate()[0], for windows environment.

**Comment by varp** [comment] 2017-09-20 09:40
Hello @elvenwhite I've already done refactoring of the whole codebase. In a couple of days I'll make a new release.

**Comment by varp** [comment] 2017-10-20 07:10
@elvenwhite the problem is fixed in the refactor branch. Can you confirm this?

**Comment by varp** [comment] 2017-12-12 13:29
@mayrino the issue is fixed in new release 2.0.0

**Closed by varp** 2017-12-12 13:29 UTC
