### ISSUE TITLE
"taskkill /F /IM node.exe" doesn't work on windows 7 ST3

### ISSUE THREAD

**Issue by spelufo** [tanepiper/SublimeText-Nodejs#42] opened 2013-08-11 18:51 UTC
Even though "taskkill /F /IM node.exe" works properly from the windows command line, it doesn't from ST3 .build-system file.

**Comment by varp** [comment] 2017-10-20 07:13
The issue is fixed in the refactor branch

**Closed by varp** 2017-10-20 07:13 UTC
