### ISSUE TITLE
ImportError libpython3.3

### ISSUE THREAD

**Issue by denis-migdal** [tanepiper/SublimeText-Nodejs#94] opened 2018-08-31 17:32 UTC
Hi,

I recently installed Nodejs from the package control on **Sublime-text 3.1.1 Build 3176**.

Items in the menus Tools/Nodejs/[Run|Debug/NPM] where disabled.
In Sublime Text's console I got the following error: 

> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
>     m = importlib.import_module(modulename)
>   File "./python3.3/importlib/__init__.py", line 90, in import_module
>   File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
>   File "<frozen importlib._bootstrap>", line 1022, in load_module
>   File "<frozen importlib._bootstrap>", line 1003, in load_module
>   File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
>   File "<frozen importlib._bootstrap>", line 868, in _load_module
>   File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
>   File "/export/home/migdal/.config/sublime-text-3/Packages/Nodejs/Nodejs.py", line 27, in <module>
>     from .lib.nodejs_commands import *
>   File "/export/home/migdal/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_commands.py", line 7, in <module>
>     from .nodejs_base import *
>   File "/export/home/migdal/.config/sublime-text-3/Packages/Nodejs/lib/nodejs_base.py", line 9, in <module>
>     import psutil
>   File "/export/home/migdal/.config/sublime-text-3/Packages/psutil/st3_linux_x64/psutil/__init__.py", line 99, in <module>
>     from . import _pslinux as _psplatform
>   File "/export/home/migdal/.config/sublime-text-3/Packages/psutil/st3_linux_x64/psutil/_pslinux.py", line 26, in <module>
>     from . import _psutil_linux as cext
> ImportError: libpython3.3m.so.1.0: cannot open shared object file: No such file or directory

I found out that **python3.3** was not installed in my computer. After installing it, it worked just fine.

On **Ubuntu 16.04.10** I installed **python3.3** with the following commands:
```
aptitude install python-software-properties
add-apt-repository ppa:deadsnakes/ppa
aptitude update
aptitude install python3.3 libpython3.3
```
On **Debian Jessie**
```
cat << EOF > /etc/apt/sources.list.d/deadsnakes.list
deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu trusty main 
deb-src http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu trusty main 
EOF
gpg --keyserver keyserver.ubuntu.com --recv-keys DB82666C
gpg --export DB82666C | sudo apt-key add -
aptitude update
aptitude install python3.3 libpython3.3
```

I hope it help if somebody get the same issue.

I think that a more explicit error message should be added.

**Comment by varp** [comment] 2018-09-08 15:00
@denis-migdal Thx. There is a related [bug](https://github.com/varp/sublime-psutil/issues/2) with `psutil` package which is shipped with the last release of the plugin.

**Comment by varp** [comment] 2019-03-21 17:25
@denis-migdal I've made a new release of the related psutil package. The bug should be fixed. Please check out.

**Comment by varp** [comment] 2019-03-22 14:53
The issue is resolved in the related package `psutil`

**Closed by varp** 2019-03-22 14:53 UTC
