### ISSUE TITLE
ImportError: No module named command_thread

### ISSUE THREAD

**Issue by bhadra** [tanepiper/SublimeText-Nodejs#47] opened 2013-10-08 13:30 UTC
On Sublime Text 2.0.2 (Windows 7), I always get the following error message in the Sublime Text console whenever Sublime Text is started. Uninstalling and reinstalling the package did not solve the problem.

Reloading plugin C:\Users\insrkum\AppData\Roaming\Sublime Text 2\Packages\Nodejs\Nodejs.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".\Nodejs.py", line 6, in <module>
    from lib.command_thread import CommandThread
ImportError: No module named command_thread
Reloading plugin C:\Users\insrkum\AppData\Roaming\Sublime Text 2\Packages\Nodejs__init__.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".__init__.py", line 1, in <module>
    from Nodejs import *
  File ".\Nodejs.py", line 6, in <module>
    from lib.command_thread import CommandThread
ImportError: No module named command_thread
Reloading plugin C:\Users\insrkum\AppData\Roaming\Sublime Text 2\Packages\Package Control\Package Control.py

**Comment by varp** [comment] 2017-08-13 11:26
@bhadra Did the issue solved in the future releases?

**Comment by varp** [comment] 2017-10-20 07:11
The issue is fixed in the refactor branch

**Closed by varp** 2017-10-20 07:11 UTC
